services:
  db:
    image: postgres:16
    container_name: whisper
    restart: always
    environment:
      POSTGRES_USER: ${LOCAL_DATABASE_USER}
      POSTGRES_PASSWORD: ${LOCAL_DATABASE_PASSWORD}
      POSTGRES_DB: ${LOCAL_DATABASE_NAME}
    ports:
      - '${LOCAL_DATABASE_PORT}:5432'
